// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

var input = Fs.readFileSync("./src/day05.txt", "utf8");

var match = input.trim().split("\n\n");

var match$1;

if (match.length !== 2) {
  match$1 = [
    "",
    []
  ];
} else {
  var state = match[0];
  var instructions = match[1];
  match$1 = [
    state,
    instructions.trim().split("\n")
  ];
}

var state$1 = match$1[0];

console.log(state$1);

var instructions$1 = match$1[1];

exports.input = input;
exports.state = state$1;
exports.instructions = instructions$1;
/* input Not a pure module */
